# Generated by Django 5.1.5 on 2025-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('regulatory', models.CharField(blank=True, max_length=1000)),
                ('regShort', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=400, null=True)),
                ('continent', models.CharField(max_length=400, null=True)),
                ('gptSummary', models.TextField(blank=True, null=True)),
                ('krimaType', models.CharField(blank=True, max_length=400, null=True)),
                ('companyName', models.CharField(blank=True, max_length=500, null=True)),
                ('currencyName', models.CharField(blank=True, max_length=300, null=True)),
                ('regulation', models.TextField(blank=True, null=True)),
                ('activityOrService', models.TextField(blank=True, null=True)),
                ('penaltyVailidate', models.CharField(blank=True, max_length=500, null=True)),
                ('penaltyCleansed', models.CharField(blank=True, max_length=500, null=True)),
                ('disgorgementRestitution', models.CharField(blank=True, max_length=500, null=True)),
                ('prejudgementInterest', models.CharField(blank=True, max_length=500, null=True)),
                ('civilPenalty', models.CharField(blank=True, max_length=500, null=True)),
                ('imposedPenalty', models.CharField(blank=True, max_length=500, null=True)),
                ('settledValue', models.CharField(blank=True, max_length=500, null=True)),
                ('nonMonetaryPenalty', models.CharField(blank=True, max_length=500, null=True)),
                ('trueFalse', models.CharField(blank=True, max_length=500, null=True)),
                ('personOrBusiness', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataBaseFile', models.FileField(upload_to='database')),
                ('dataTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
