# Generated by Django 5.1.3 on 2025-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_krimacompanydata_delete_companydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='krimacompanydata',
            name='RegFullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
